server:
  port: 9088
  servlet:
    context-path: /account-center
  mail: #邮件服务配置
    #smtp服务主机，目前使用QQ邮箱
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 601878125@qq.com
    #授权码
    password: sdxelsqergvrbdgj
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://192.168.3.2:3306/archimedes?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.zaxxer.hikari.HikariDataSource
    username: root
    password: sakula424KA!@#