server:
  port: 9088
  servlet:
    context-path: /account-center
spring:
  application:
    name: account
  profiles:
    active: local
    group:
      local: public
  datasource:
    url: jdbc:mysql://192.168.3.32:3306/account?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sakula424KA
  data:
    redis:
      host: 192.168.3.32
      port: 6379
mybatis:
  mapper-locations: classpath*:mapper/*.xml