spring:
  cloud:
    inetutils:
      timeout-seconds: 10
  mail: #邮件服务配置
    #smtp服务主机，目前使用QQ邮箱
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 601878125@qq.com
    #授权码
    password: sdxelsqergvrbdgj
    test-connection: true
#logging:
#  pattern:
#    dateformat: yyyy-MM-dd HH:mm:ss
#    console: ${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){cyan} %clr(${LOG_LEVEL_PATTERN:[%5p]}) %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}
#  level:
#    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
#  config: classpath:logback-spring.xml