spring:
  cloud:
    inetutils:
      timeout-seconds: 10
  mail: #邮件服务配置
    #smtp服务主机，目前使用QQ邮箱
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 601878125@qq.com
    #授权码
    password: sdxelsqergvrbdgj
    test-connection: true
  data:
    redis:
      host: 192.168.3.32
      port: 6379
system:
  internal:
    secret: e9ZnRzYnDk6TyhXvLsQ3B7s8pVjwFc4J
    admin:
      id: af26a89c168946ce84041a08da148216
logging:
  config: classpath:log4j2.xml